-- =========================================================================
-- 003 — Extension du périmètre : opérateurs télécoms africains
--
-- FICHIER GÉNÉRÉ par tools/generate_migration_003.py depuis
-- config/operators.json. Ne pas éditer à la main : régénérer après toute
-- modification de la configuration, sinon les alias divergent des noms
-- publiés par les collecteurs et les avis cessent de se rattacher.
--
-- Idempotent (ON CONFLICT DO NOTHING) : rejouable sans effet de bord.
-- =========================================================================

BEGIN;

-- Pays ---------------------------------------------------------------
INSERT INTO dim_country (iso2, iso3, name, region) VALUES
    ('AO', 'AGO', 'Angola', 'Afrique australe'),
    ('BF', 'BFA', 'Burkina Faso', 'Afrique de l''Ouest'),
    ('BI', 'BDI', 'Burundi', 'Afrique de l''Est'),
    ('BJ', 'BEN', 'Bénin', 'Afrique de l''Ouest'),
    ('BW', 'BWA', 'Botswana', 'Afrique australe'),
    ('CD', 'COD', 'RD Congo', 'Afrique centrale'),
    ('CF', 'CAF', 'Centrafrique', 'Afrique centrale'),
    ('CG', 'COG', 'Congo-Brazzaville', 'Afrique centrale'),
    ('CI', 'CIV', 'Côte d''Ivoire', 'Afrique de l''Ouest'),
    ('CM', 'CMR', 'Cameroun', 'Afrique centrale'),
    ('CV', 'CPV', 'Cap-Vert', 'Afrique de l''Ouest'),
    ('DJ', 'DJI', 'Djibouti', 'Afrique de l''Est'),
    ('DZ', 'DZA', 'Algérie', 'Afrique du Nord'),
    ('EG', 'EGY', 'Égypte', 'Afrique du Nord'),
    ('ER', 'ERI', 'Érythrée', 'Afrique de l''Est'),
    ('ET', 'ETH', 'Éthiopie', 'Afrique de l''Est'),
    ('GA', 'GAB', 'Gabon', 'Afrique centrale'),
    ('GH', 'GHA', 'Ghana', 'Afrique de l''Ouest'),
    ('GM', 'GMB', 'Gambie', 'Afrique de l''Ouest'),
    ('GN', 'GIN', 'Guinée', 'Afrique de l''Ouest'),
    ('GQ', 'GNQ', 'Guinée équatoriale', 'Afrique centrale'),
    ('GW', 'GNB', 'Guinée-Bissau', 'Afrique de l''Ouest'),
    ('KE', 'KEN', 'Kenya', 'Afrique de l''Est'),
    ('KM', 'COM', 'Comores', 'Afrique de l''Est'),
    ('LR', 'LBR', 'Liberia', 'Afrique de l''Ouest'),
    ('LS', 'LSO', 'Lesotho', 'Afrique australe'),
    ('LY', 'LBY', 'Libye', 'Afrique du Nord'),
    ('MA', 'MAR', 'Maroc', 'Afrique du Nord'),
    ('MG', 'MDG', 'Madagascar', 'Afrique de l''Est'),
    ('ML', 'MLI', 'Mali', 'Afrique de l''Ouest'),
    ('MR', 'MRT', 'Mauritanie', 'Afrique de l''Ouest'),
    ('MU', 'MUS', 'Maurice', 'Afrique de l''Est'),
    ('MW', 'MWI', 'Malawi', 'Afrique australe'),
    ('MZ', 'MOZ', 'Mozambique', 'Afrique australe'),
    ('NA', 'NAM', 'Namibie', 'Afrique australe'),
    ('NE', 'NER', 'Niger', 'Afrique de l''Ouest'),
    ('NG', 'NGA', 'Nigeria', 'Afrique de l''Ouest'),
    ('RW', 'RWA', 'Rwanda', 'Afrique de l''Est'),
    ('SC', 'SYC', 'Seychelles', 'Afrique de l''Est'),
    ('SD', 'SDN', 'Soudan', 'Afrique du Nord'),
    ('SL', 'SLE', 'Sierra Leone', 'Afrique de l''Ouest'),
    ('SN', 'SEN', 'Sénégal', 'Afrique de l''Ouest'),
    ('SO', 'SOM', 'Somalie', 'Afrique de l''Est'),
    ('SS', 'SSD', 'Soudan du Sud', 'Afrique de l''Est'),
    ('ST', 'STP', 'Sao Tomé-et-Principe', 'Afrique centrale'),
    ('SZ', 'SWZ', 'eSwatini', 'Afrique australe'),
    ('TD', 'TCD', 'Tchad', 'Afrique centrale'),
    ('TG', 'TGO', 'Togo', 'Afrique de l''Ouest'),
    ('TN', 'TUN', 'Tunisie', 'Afrique du Nord'),
    ('TZ', 'TZA', 'Tanzanie', 'Afrique de l''Est'),
    ('UG', 'UGA', 'Ouganda', 'Afrique de l''Est'),
    ('ZA', 'ZAF', 'Afrique du Sud', 'Afrique australe'),
    ('ZM', 'ZMB', 'Zambie', 'Afrique australe'),
    ('ZW', 'ZWE', 'Zimbabwe', 'Afrique australe')
ON CONFLICT (iso2) DO NOTHING;

-- Opérateurs ---------------------------------------------------------
INSERT INTO dim_operator (code, name, parent_group, former_names) VALUES
    ('nine_mobile', '9mobile', NULL, ARRAY['Etisalat Nigeria']::text[]),
    ('africell', 'Africell', 'Africell Holding', ARRAY[]::text[]),
    ('airtel', 'Airtel', 'Bharti Airtel', ARRAY['Zain Africa', 'Celtel']::text[]),
    ('airteltigo', 'AirtelTigo', NULL, ARRAY['Tigo Ghana']::text[]),
    ('almadar', 'Almadar', 'Libyan Post Telecom', ARRAY['Almadar Aljadid']::text[]),
    ('btc', 'BTC', 'Botswana Telecommunications', ARRAY['beMobile']::text[]),
    ('cst', 'CST', 'Companhia Santomense de Telecomunicações', ARRAY[]::text[]),
    ('cvmovel', 'CVMovel', 'Cabo Verde Telecom', ARRAY[]::text[]),
    ('cable_wireless', 'Cable & Wireless', 'Cable & Wireless', ARRAY[]::text[]),
    ('camtel', 'Camtel', NULL, ARRAY[]::text[]),
    ('cell_c', 'Cell C', NULL, ARRAY[]::text[]),
    ('celtiis', 'Celtiis', 'Bénin Telecoms', ARRAY[]::text[]),
    ('chinguitel', 'Chinguitel', 'Sudatel', ARRAY[]::text[]),
    ('comores_telecom', 'Comores Telecom', NULL, ARRAY['Huri']::text[]),
    ('djezzy', 'Djezzy', 'Veon', ARRAY['Orascom Telecom']::text[]),
    ('djibouti_telecom', 'Djibouti Telecom', NULL, ARRAY['Evatis']::text[]),
    ('econet', 'Econet', 'Econet Wireless', ARRAY[]::text[]),
    ('emtel', 'Emtel', NULL, ARRAY[]::text[]),
    ('eritel', 'EriTel', NULL, ARRAY['Eritrea Telecommunication']::text[]),
    ('eswatini_mobile', 'Eswatini Mobile', NULL, ARRAY[]::text[]),
    ('ethio_telecom', 'Ethio Telecom', NULL, ARRAY[]::text[]),
    ('expresso', 'Expresso', 'Sudatel', ARRAY[]::text[]),
    ('free_senegal', 'Free Sénégal', 'Axian', ARRAY['Tigo Sénégal']::text[]),
    ('getesa', 'GETESA', 'Orange S.A.', ARRAY['Orange Guinée équatoriale']::text[]),
    ('gamcel', 'Gamcel', 'Gamtel', ARRAY[]::text[]),
    ('glo', 'Glo', 'Globacom', ARRAY[]::text[]),
    ('halotel', 'Halotel', 'Viettel', ARRAY[]::text[]),
    ('hormuud', 'Hormuud', 'Hormuud Telecom', ARRAY[]::text[]),
    ('inwi', 'Inwi', 'Al Mada', ARRAY['Wana']::text[]),
    ('libyana', 'Libyana', 'Libyan Post Telecom', ARRAY[]::text[]),
    ('lumitel', 'Lumitel', 'Viettel', ARRAY[]::text[]),
    ('mtc', 'MTC', 'Mobile Telecommunications Ltd', ARRAY[]::text[]),
    ('mtn', 'MTN', 'MTN Group', ARRAY[]::text[]),
    ('maroc_telecom', 'Maroc Telecom', 'e& (Etisalat Group)', ARRAY['IAM']::text[]),
    ('mascom', 'Mascom', 'Mascom Wireless', ARRAY[]::text[]),
    ('mattel', 'Mattel', 'Tunisie Telecom', ARRAY[]::text[]),
    ('mauritel', 'Mauritel', 'Maroc Telecom', ARRAY[]::text[]),
    ('mauritius_telecom', 'Mauritius Telecom', NULL, ARRAY['my.t', 'Orange Mauritius']::text[]),
    ('mobilis', 'Mobilis', 'Algérie Télécom', ARRAY['ATM']::text[]),
    ('moov_africa', 'Moov Africa', 'Maroc Telecom', ARRAY['Etisalat', 'Telecel']::text[]),
    ('movicel', 'Movicel', NULL, ARRAY[]::text[]),
    ('movitel', 'Movitel', 'Viettel', ARRAY[]::text[]),
    ('netone', 'NetOne', NULL, ARRAY[]::text[]),
    ('onatel_burundi', 'Onatel Burundi', 'Maroc Telecom', ARRAY['Smart Burundi']::text[]),
    ('ooredoo', 'Ooredoo', 'Ooredoo Group', ARRAY[]::text[]),
    ('orange', 'Orange', 'Orange S.A.', ARRAY['Sonatel']::text[]),
    ('qcell', 'QCell', NULL, ARRAY[]::text[]),
    ('safaricom', 'Safaricom', 'Vodacom / Vodafone', ARRAY[]::text[]),
    ('somtel', 'Somtel', 'Dahabshiil Group', ARRAY[]::text[]),
    ('sotel_tchad', 'Sotel Tchad', NULL, ARRAY['Salam']::text[]),
    ('tn_mobile', 'TN Mobile', 'Telecom Namibia', ARRAY['Leo']::text[]),
    ('tnm', 'TNM', NULL, ARRAY['Telekom Networks Malawi']::text[]),
    ('telecel', 'Telecel', 'Telecel Group', ARRAY[]::text[]),
    ('telesom', 'Telesom', NULL, ARRAY[]::text[]),
    ('telkom', 'Telkom', NULL, ARRAY[]::text[]),
    ('telma', 'Telma', 'Axian', ARRAY[]::text[]),
    ('tmcel', 'Tmcel', NULL, ARRAY['mCel', 'Telecomunicações de Moçambique']::text[]),
    ('togocom', 'Togocom', 'Axian', ARRAY['Togo Telecom', 'Togo Cellulaire']::text[]),
    ('unitel', 'Unitel', NULL, ARRAY[]::text[]),
    ('vodacom', 'Vodacom', 'Vodafone Group', ARRAY[]::text[]),
    ('vodafone', 'Vodafone', 'Vodafone Group', ARRAY[]::text[]),
    ('we', 'WE', 'Telecom Egypt', ARRAY['Telecom Egypt', 'WE Telecom Egypt']::text[]),
    ('zain', 'Zain', 'Zain Group', ARRAY[]::text[]),
    ('zamtel', 'Zamtel', 'Zambia Telecommunications Company', ARRAY['Zamtel Zambia', 'Zambia Telecommunications']::text[]),
    ('e_and', 'e&', 'e& (Emirates Telecommunications Group)', ARRAY['Etisalat', 'Etisalat Egypt', 'Etisalat Misr', 'e& Egypt']::text[])
ON CONFLICT (code) DO NOTHING;

-- Filiales -----------------------------------------------------------
--   aliases = les noms exacts publiés par les collecteurs, d'où le
--   rattachement automatique de reviews.company -> subsidiary_id.
INSERT INTO dim_subsidiary (operator_id, country_id, name, aliases)
SELECT o.operator_id, c.country_id, v.name, v.aliases
FROM (VALUES
        ('cell_c', 'ZA', 'Cell C', ARRAY['Cell C', 'Cell C Afrique du Sud']::text[]),
        ('mtn', 'ZA', 'MTN South Africa', ARRAY['MTN Afrique du Sud', 'MTN South Africa']::text[]),
        ('telkom', 'ZA', 'Telkom South Africa', ARRAY['Telkom Afrique du Sud', 'Telkom South Africa']::text[]),
        ('vodacom', 'ZA', 'Vodacom South Africa', ARRAY['Vodacom Afrique du Sud', 'Vodacom South Africa']::text[]),
        ('djezzy', 'DZ', 'Djezzy', ARRAY['Djezzy', 'Djezzy Algérie']::text[]),
        ('mobilis', 'DZ', 'Mobilis', ARRAY['Mobilis', 'Mobilis Algérie']::text[]),
        ('ooredoo', 'DZ', 'Ooredoo Algérie', ARRAY['Ooredoo Algerie', 'Ooredoo Algérie']::text[]),
        ('africell', 'AO', 'Africell Angola', ARRAY['Africell Angola']::text[]),
        ('movicel', 'AO', 'Movicel', ARRAY['Movicel', 'Movicel Angola']::text[]),
        ('unitel', 'AO', 'Unitel Angola', ARRAY['Unitel Angola']::text[]),
        ('btc', 'BW', 'BTC Botswana', ARRAY['BTC Botswana']::text[]),
        ('mascom', 'BW', 'Mascom', ARRAY['Mascom', 'Mascom Botswana']::text[]),
        ('orange', 'BW', 'Orange Botswana', ARRAY['Orange Botswana']::text[]),
        ('moov_africa', 'BF', 'Moov Africa Burkina', ARRAY['Moov Africa Burkina', 'Moov Africa Burkina Faso']::text[]),
        ('orange', 'BF', 'Orange Burkina Faso', ARRAY['Orange Burkina Faso']::text[]),
        ('econet', 'BI', 'Econet Burundi', ARRAY['Econet Burundi']::text[]),
        ('lumitel', 'BI', 'Lumitel', ARRAY['Lumitel', 'Lumitel Burundi']::text[]),
        ('onatel_burundi', 'BI', 'Onatel Burundi', ARRAY['Onatel Burundi', 'Onatel Burundi Burundi']::text[]),
        ('celtiis', 'BJ', 'Celtiis', ARRAY['Celtiis', 'Celtiis Bénin']::text[]),
        ('mtn', 'BJ', 'MTN Bénin', ARRAY['MTN Bénin']::text[]),
        ('moov_africa', 'BJ', 'Moov Africa Benin', ARRAY['Moov Africa Benin', 'Moov Africa Bénin']::text[]),
        ('camtel', 'CM', 'Camtel', ARRAY['Camtel', 'Camtel Cameroun']::text[]),
        ('mtn', 'CM', 'MTN Cameroun', ARRAY['MTN Cameroun']::text[]),
        ('orange', 'CM', 'Orange Cameroun', ARRAY['Orange Cameroun']::text[]),
        ('cvmovel', 'CV', 'CVMovel', ARRAY['CVMovel', 'CVMovel Cap-Vert']::text[]),
        ('unitel', 'CV', 'Unitel T+', ARRAY['Unitel Cap-Vert', 'Unitel T+']::text[]),
        ('moov_africa', 'CF', 'Moov Africa Centrafrique', ARRAY['Moov Africa Centrafrique']::text[]),
        ('telecel', 'CF', 'Telecel Centrafrique', ARRAY['Telecel Centrafrique']::text[]),
        ('comores_telecom', 'KM', 'Comores Telecom', ARRAY['Comores Telecom', 'Comores Telecom Comores']::text[]),
        ('telma', 'KM', 'Telma Comores', ARRAY['Telma Comores']::text[]),
        ('airtel', 'CG', 'Airtel Congo', ARRAY['Airtel Congo', 'Airtel Congo Brazzaville', 'Airtel Congo-Brazzaville']::text[]),
        ('mtn', 'CG', 'MTN Congo', ARRAY['MTN Congo', 'MTN Congo Brazzaville', 'MTN Congo-Brazzaville']::text[]),
        ('orange', 'CG', 'Orange Congo', ARRAY['Orange Congo', 'Orange Congo Brazzaville', 'Orange Congo-Brazzaville']::text[]),
        ('mtn', 'CI', 'MTN Côte d''Ivoire', ARRAY['MTN Côte d''Ivoire']::text[]),
        ('moov_africa', 'CI', 'Moov Africa Côte d''Ivoire', ARRAY['Moov Africa Côte d''Ivoire']::text[]),
        ('orange', 'CI', 'Orange Côte d''Ivoire', ARRAY['Orange Côte d''Ivoire']::text[]),
        ('djibouti_telecom', 'DJ', 'Djibouti Telecom', ARRAY['Djibouti Telecom', 'Djibouti Telecom Djibouti']::text[]),
        ('airtel', 'GA', 'Airtel Gabon', ARRAY['Airtel Gabon']::text[]),
        ('moov_africa', 'GA', 'Moov Africa Gabon', ARRAY['Moov Africa Gabon']::text[]),
        ('africell', 'GM', 'Africell Gambie', ARRAY['Africell Gambie']::text[]),
        ('gamcel', 'GM', 'Gamcel', ARRAY['Gamcel', 'Gamcel Gambie']::text[]),
        ('qcell', 'GM', 'QCell', ARRAY['QCell', 'QCell Gambie']::text[]),
        ('airteltigo', 'GH', 'AirtelTigo Ghana', ARRAY['AirtelTigo Ghana']::text[]),
        ('mtn', 'GH', 'MTN Ghana', ARRAY['MTN Ghana']::text[]),
        ('vodafone', 'GH', 'Vodafone Ghana', ARRAY['Vodafone Ghana']::text[]),
        ('mtn', 'GN', 'MTN Guinée-Conakry', ARRAY['MTN Guinée', 'MTN Guinée Conakry', 'MTN Guinée-Conakry']::text[]),
        ('orange', 'GN', 'Orange Guinée', ARRAY['Orange Guinée']::text[]),
        ('getesa', 'GQ', 'GETESA', ARRAY['GETESA', 'GETESA Guinée équatoriale']::text[]),
        ('mtn', 'GW', 'MTN Guinée-Bissau', ARRAY['MTN Guinée-Bissau']::text[]),
        ('orange', 'GW', 'Orange Guinée-Bissau', ARRAY['Orange Guinée-Bissau']::text[]),
        ('airtel', 'KE', 'Airtel Kenya', ARRAY['Airtel Kenya']::text[]),
        ('safaricom', 'KE', 'Safaricom Kenya', ARRAY['Safaricom Kenya']::text[]),
        ('telkom', 'KE', 'Telkom Kenya', ARRAY['Telkom Kenya']::text[]),
        ('econet', 'LS', 'Econet Lesotho', ARRAY['Econet Lesotho', 'Econet Telecom Lesotho']::text[]),
        ('vodacom', 'LS', 'Vodacom Lesotho', ARRAY['Vodacom Lesotho']::text[]),
        ('mtn', 'LR', 'MTN Liberia', ARRAY['MTN Liberia']::text[]),
        ('orange', 'LR', 'Orange Liberia', ARRAY['Orange Liberia']::text[]),
        ('almadar', 'LY', 'Almadar Aljadid', ARRAY['Almadar Aljadid', 'Almadar Libye']::text[]),
        ('libyana', 'LY', 'Libyana', ARRAY['Libyana', 'Libyana Libye']::text[]),
        ('airtel', 'MG', 'Airtel Madagascar', ARRAY['Airtel Madagascar']::text[]),
        ('orange', 'MG', 'Orange Madagascar', ARRAY['Orange Madagascar']::text[]),
        ('telma', 'MG', 'Telma', ARRAY['Telma', 'Telma Madagascar']::text[]),
        ('airtel', 'MW', 'Airtel Malawi', ARRAY['Airtel Malawi']::text[]),
        ('tnm', 'MW', 'TNM Malawi', ARRAY['TNM Malawi']::text[]),
        ('moov_africa', 'ML', 'Moov Africa Mali', ARRAY['Moov Africa Mali']::text[]),
        ('orange', 'ML', 'Orange Mali', ARRAY['Orange Mali']::text[]),
        ('inwi', 'MA', 'Inwi', ARRAY['Inwi', 'Inwi Maroc']::text[]),
        ('maroc_telecom', 'MA', 'Maroc Telecom', ARRAY['Maroc Telecom', 'Maroc Telecom Maroc']::text[]),
        ('orange', 'MA', 'Orange Maroc', ARRAY['Orange Maroc']::text[]),
        ('emtel', 'MU', 'Emtel', ARRAY['Emtel', 'Emtel Maurice']::text[]),
        ('mauritius_telecom', 'MU', 'Mauritius Telecom', ARRAY['Mauritius Telecom', 'Mauritius Telecom Maurice']::text[]),
        ('chinguitel', 'MR', 'Chinguitel', ARRAY['Chinguitel', 'Chinguitel Mauritanie']::text[]),
        ('mattel', 'MR', 'Mattel', ARRAY['Mattel', 'Mattel Mauritanie']::text[]),
        ('mauritel', 'MR', 'Mauritel', ARRAY['Mauritel', 'Mauritel Mauritanie']::text[]),
        ('movitel', 'MZ', 'Movitel', ARRAY['Movitel', 'Movitel Mozambique']::text[]),
        ('tmcel', 'MZ', 'Tmcel', ARRAY['Tmcel', 'Tmcel Mozambique']::text[]),
        ('vodacom', 'MZ', 'Vodacom Mozambique', ARRAY['Vodacom Mozambique']::text[]),
        ('mtc', 'NA', 'MTC Namibie', ARRAY['MTC Namibie']::text[]),
        ('tn_mobile', 'NA', 'TN Mobile', ARRAY['TN Mobile', 'TN Mobile Namibie']::text[]),
        ('airtel', 'NE', 'Airtel Niger', ARRAY['Airtel Niger']::text[]),
        ('moov_africa', 'NE', 'Moov Africa Niger', ARRAY['Moov Africa Niger']::text[]),
        ('orange', 'NE', 'Orange Niger', ARRAY['Orange Niger']::text[]),
        ('nine_mobile', 'NG', '9mobile', ARRAY['9mobile', '9mobile Nigeria']::text[]),
        ('airtel', 'NG', 'Airtel Nigeria', ARRAY['Airtel Nigeria']::text[]),
        ('glo', 'NG', 'Glo Nigeria', ARRAY['Glo Nigeria', 'Globacom Nigeria']::text[]),
        ('mtn', 'NG', 'MTN Nigeria', ARRAY['MTN Nigeria']::text[]),
        ('airtel', 'UG', 'Airtel Ouganda', ARRAY['Airtel Ouganda', 'Airtel Uganda']::text[]),
        ('mtn', 'UG', 'MTN Ouganda', ARRAY['MTN Ouganda', 'MTN Uganda']::text[]),
        ('africell', 'CD', 'Africell RDC', ARRAY['Africell RD Congo', 'Africell RDC']::text[]),
        ('airtel', 'CD', 'Airtel RDC', ARRAY['Airtel RD Congo', 'Airtel RDC']::text[]),
        ('mtn', 'CD', 'MTN RDC', ARRAY['MTN RD Congo', 'MTN RDC']::text[]),
        ('orange', 'CD', 'Orange RDC', ARRAY['Orange RD Congo', 'Orange RDC']::text[]),
        ('vodacom', 'CD', 'Vodacom RDC', ARRAY['Vodacom RD Congo', 'Vodacom RDC']::text[]),
        ('airtel', 'RW', 'Airtel Rwanda', ARRAY['Airtel Rwanda']::text[]),
        ('mtn', 'RW', 'MTN Rwanda', ARRAY['MTN Rwanda']::text[]),
        ('cst', 'ST', 'CST', ARRAY['CST', 'CST Sao Tomé-et-Principe']::text[]),
        ('unitel', 'ST', 'Unitel STP', ARRAY['Unitel STP', 'Unitel Sao Tomé-et-Principe']::text[]),
        ('airtel', 'SC', 'Airtel Seychelles', ARRAY['Airtel Seychelles']::text[]),
        ('cable_wireless', 'SC', 'Cable & Wireless Seychelles', ARRAY['Cable & Wireless Seychelles', 'Cable Wireless Seychelles']::text[]),
        ('africell', 'SL', 'Africell Sierra Leone', ARRAY['Africell Sierra Leone']::text[]),
        ('orange', 'SL', 'Orange Sierra Leone', ARRAY['Orange Sierra Leone']::text[]),
        ('hormuud', 'SO', 'Hormuud', ARRAY['Hormuud', 'Hormuud Somalie']::text[]),
        ('somtel', 'SO', 'Somtel', ARRAY['Somtel', 'Somtel Somalie']::text[]),
        ('telesom', 'SO', 'Telesom', ARRAY['Telesom', 'Telesom Somalie']::text[]),
        ('mtn', 'SD', 'MTN Soudan', ARRAY['MTN Soudan', 'MTN Sudan']::text[]),
        ('zain', 'SD', 'Zain Soudan', ARRAY['Zain Soudan', 'Zain Sudan']::text[]),
        ('mtn', 'SS', 'MTN Soudan du Sud', ARRAY['MTN Soudan du Sud', 'MTN South Sudan']::text[]),
        ('zain', 'SS', 'Zain Soudan du Sud', ARRAY['Zain Soudan du Sud', 'Zain South Sudan']::text[]),
        ('expresso', 'SN', 'Expresso Sénégal', ARRAY['Expresso Sénégal']::text[]),
        ('free_senegal', 'SN', 'Free Sénégal', ARRAY['Free Sénégal', 'Free Sénégal Sénégal', 'Free Sénégal opérateur']::text[]),
        ('orange', 'SN', 'Orange Sénégal', ARRAY['Orange Sénégal']::text[]),
        ('airtel', 'TZ', 'Airtel Tanzanie', ARRAY['Airtel Tanzania', 'Airtel Tanzanie']::text[]),
        ('halotel', 'TZ', 'Halotel Tanzanie', ARRAY['Halotel Tanzania', 'Halotel Tanzanie']::text[]),
        ('vodacom', 'TZ', 'Vodacom Tanzanie', ARRAY['Vodacom Tanzania', 'Vodacom Tanzanie']::text[]),
        ('airtel', 'TD', 'Airtel Tchad', ARRAY['Airtel Tchad']::text[]),
        ('sotel_tchad', 'TD', 'Sotel Tchad', ARRAY['Sotel Tchad', 'Sotel Tchad Tchad']::text[]),
        ('moov_africa', 'TG', 'Moov Africa Togo', ARRAY['Moov Africa Togo']::text[]),
        ('togocom', 'TG', 'Togocom', ARRAY['Togocom', 'Togocom Togo']::text[]),
        ('ooredoo', 'TN', 'Ooredoo Tunisie', ARRAY['Ooredoo Tunisie']::text[]),
        ('orange', 'TN', 'Orange Tunisie', ARRAY['Orange Tunisie']::text[]),
        ('airtel', 'ZM', 'Airtel Zambie', ARRAY['Airtel Zambia', 'Airtel Zambie']::text[]),
        ('mtn', 'ZM', 'MTN Zambie', ARRAY['MTN Zambia', 'MTN Zambie']::text[]),
        ('zamtel', 'ZM', 'Zamtel Zambie', ARRAY['Zamtel Zambia', 'Zamtel Zambie']::text[]),
        ('econet', 'ZW', 'Econet Zimbabwe', ARRAY['Econet Zimbabwe']::text[]),
        ('netone', 'ZW', 'NetOne', ARRAY['NetOne', 'NetOne Zimbabwe']::text[]),
        ('telecel', 'ZW', 'Telecel Zimbabwe', ARRAY['Telecel Zimbabwe']::text[]),
        ('eswatini_mobile', 'SZ', 'Eswatini Mobile', ARRAY['Eswatini Mobile', 'Eswatini Mobile eSwatini']::text[]),
        ('mtn', 'SZ', 'MTN eSwatini', ARRAY['MTN eSwatini']::text[]),
        ('orange', 'EG', 'Orange Égypte', ARRAY['Orange Egypte', 'Orange Égypte']::text[]),
        ('vodafone', 'EG', 'Vodafone Égypte', ARRAY['Vodafone Egypte', 'Vodafone Égypte']::text[]),
        ('e_and', 'EG', 'e& Égypte', ARRAY['e& Egypt', 'e& Égypte']::text[]),
        ('we', 'EG', 'WE Égypte', ARRAY['Telecom Egypt', 'WE Égypte']::text[]),
        ('eritel', 'ER', 'EriTel', ARRAY['EriTel', 'EriTel Érythrée']::text[]),
        ('ethio_telecom', 'ET', 'Ethio Telecom', ARRAY['Ethio Telecom', 'Ethio Telecom Éthiopie']::text[]),
        ('safaricom', 'ET', 'Safaricom Éthiopie', ARRAY['Safaricom Ethiopia', 'Safaricom Éthiopie']::text[])
     ) AS v(op_code, iso2, name, aliases)
JOIN dim_country  c ON c.iso2 = v.iso2
JOIN dim_operator o ON o.code = v.op_code
-- Fusion des alias plutôt que DO NOTHING : la migration doit rester
-- rejouable après un ajout d'alias, sans perdre ceux déjà en base
-- (ex. 'Etisalat Bénin', hérité de l'ancien nom de marque).
ON CONFLICT (operator_id, country_id) DO UPDATE
SET aliases = ARRAY(
    SELECT DISTINCT unnest(dim_subsidiary.aliases || EXCLUDED.aliases)
);

COMMIT;
